adapt snap source for wine-platform

diff --git a/scripts/dl_np3 b/scripts/dl_np3
--- a/scripts/dl_np3
+++ b/scripts/dl_np3
@@ -16,8 +16,17 @@ dlnp3 () {
 
 mknp3 () {
     mkdir -p usr/share && mkdir wine-platform
+    ARCHITECTURE=$(dpkg --print-architecture)
     7z x Notepad3_${ver}.zip &> /dev/null
-    7z x Notepad3_${ver}_x86.zip -x'!Changes.txt' -x'!License.txt' -x'!Readme.txt' -o"usr/share/notepad3" &> /dev/null
+    ARCHITECTURE=$(dpkg --print-architecture)
+    if [ "${ARCHITECTURE}" = "amd64" ]; then
+     7z x Notepad3_${ver}_x64.zip -x'!Changes.txt' -x'!License.txt' -x'!Readme.txt' -o"usr/share/notepad3" &> /dev/null
+    elif [ "${ARCHITECTURE}" = "i386" ]; then
+     7z x Notepad3_${ver}_x86.zip -x'!Changes.txt' -x'!License.txt' -x'!Readme.txt' -o"usr/share/notepad3" &> /dev/null
+    else
+     echo "ERROR! Notepad3 only produces software for amd64 and i386. Failing the build here."
+     exit 1
+    fi
     mv usr/share/notepad3/Notepad3.exe usr/share/notepad3/notepad3.exe
     find "usr" -type d -execdir chmod 755 {} +
     mkdir -p usr/share/pixmaps && mkdir -p usr/share/applications && mkdir bin
